

cat:
  name: resources下/system-tom

config:
  #string: 字符串
  date: 2021/11/20 08:53:00
  integer: 10
  map:
    name: zhengjun
  strings:
    - 1
    - 2
  list:
    - 3
    - 4
  list-map:
    city:
      - zhengzhou
      - wuhan
  map-list:
    - job: kaifa
    - city: shanghai
  security:
    username: zhangsan
    password: 123456