
cat:
  name: tom

config:
  string: 字符串
  date: 2021/11/20 08:53:00
  integer: 10
  map:
    name: zhengjun
  list-map:
    city:
      - zhengzhou
      - wuhan
  map-list:
    - job:
        name: kaifa
        year: 2
    - city:
        name: shanghai


